### ISSUE TITLE
link: github.com/arnodel/golua/runtime: invalid reference to runtime.int64Hash

### ISSUE THREAD

**Issue by sammy-ette** [arnodel/golua#105]
Go 1.23 makes a change which causes golua to not link/build/whatever without the specific flag that allows the behavior the new release blocks. Is the only solution to use that flag, or can this be fixed here?

**Comment by arnodel** [comment]
There is  a proposal (https://github.com/golang/go/issues/54670), which has been accepted, which might be able to be used instead.  In the meantime I would need to implement some hashing functions which will likely be slower (haven't measured it!).

**Comment by arnodel** [comment]
I had a little bit of time to look at this issue.  It is because of this change to the linker(see [go 1.23 release notes](https://tip.golang.org/doc/go1.23#linker))

>The linker now disallows using a //go:linkname directive to refer to internal symbols in the standard library (including the runtime) that are not marked with //go:linkname on their definitions. Similarly, the linker disallows references to such symbols from assembly code. For backward compatibility, existing usages of //go:linkname found in a large open-source code corpus remain supported. Any new references to standard library internal symbols will be disallowed.
>
>A linker command line flag -checklinkname=0 can be used to disable this check, for debugging and experimenting purposes.

I will try to find the time to get a fix in, in the meantime it is still possible to build golua on go 1.23 with the `-ldflags='-checklinkname=0'` option.
